### ISSUE TITLE
Can't download more than 100 files

### ISSUE THREAD

**Issue by StephenVelez** [NicKoehler/mediafire_bulk_downloader#1]
Tried to download a large folder, it creates the files and downloads the first 100 files, but then it just ignores the rest if there are any.

**Comment by NicKoehler** [comment]
Hi, can you share the link so I can try too?

**Comment by StephenVelez** [comment]
Sure, when I try downloading something like this, you can see it only counts up the hundredth file and starts downloading the files. I tried using python3 instead since I was using python 2.x but that didn't seem to work. 

[LINK](https://www.mediafire.com/folder/akjcex4b8dgui/Documents)

**Comment by NicKoehler** [comment]
Fixed with [my last commit](https://github.com/NicKoehler/mediafire_bulk_downloader/commit/5ef1599e4c0e0f73d6a7770ebd5901c33d247814)
