### ISSUE TITLE
error when trying to download from mediafire

### ISSUE THREAD

**Issue by marwan211** [NicKoehler/mediafire_bulk_downloader#10]
here is the error  line 41, in get
    content = response.read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 160: invalid start byte

**Comment by NicKoehler** [comment]
Can you post the link?

**Comment by marwan211** [comment]
https://www.mediafire.com/folder/1nrpu0pz9enw1/Ch08_Adv_WS_Avatar_F_Island

**Comment by NicKoehler** [comment]
Mediafire changed something, now I can bulk download the entire folder from mediafire directly without paying, can you try to download from it too?

**Comment by marwan211** [comment]
will check that , thx!

**Comment by NicKoehler** [comment]
fixed with my last commit

**Comment by marwan211** [comment]
thx!
