### ISSUE TITLE
Files not downloading

### ISSUE THREAD

**Issue by starcrash-13** [NicKoehler/mediafire_bulk_downloader#13]
<img width="712" alt="Screenshot 2024-10-16 000636" src="https://github.com/user-attachments/assets/51468829-286a-4247-85aa-67a64c14bcf8">

I am getting a "Forbidden for url" error whenever I try to download files.

**Comment by NicKoehler** [comment]
You are right, something is wrong.
I'll investigate the issue.

**Comment by NicKoehler** [comment]
@starcrash-13 can you update from my repo and try again now?

**Comment by starcrash-13** [comment]
Sorry, I have been out of town, just tested and yes it's working! Thanks!
