### ISSUE TITLE
Error when Downloading Files 

### ISSUE THREAD

**Issue by Salxchange** [NicKoehler/mediafire_bulk_downloader#14]
Deleted file or Dangerous File Blocked`

am getting this error when I try to download files

**Comment by NicKoehler** [comment]
Can you post the link?

**Comment by mohammedrattia** [comment]
I have the same problem. all the files deleted after download. I don't know why. sorry I can't share the link.

**Comment by mohammedrattia** [comment]
I commented part of the mediafire.py code and it worked for me. I will try to push the edited version.
this part made the problem (the if function in line 472)
'''if response.status != 200:
        conn.close()
        print_error(download_link)
        if limiter:
            limiter.release()
        return'''

**Comment by NicKoehler** [comment]
Fixed with #16
