### ISSUE TITLE
skip download when already exist

### ISSUE THREAD

**Issue by dennisb1** [NicKoehler/mediafire_bulk_downloader#2]
Currently it downloads all files over and over again even if its already present.
Can we add a possiblity to skip these files?

**Comment by NicKoehler** [comment]
Yes it can be done, but is risky as some files may not be downloaded entirely if you interrupt the download without let it finish, maybe I add an option to skip them

**Comment by dennisb1** [comment]
It's possible to also look maybe on change date?
Dont know if thats even parsed with the way you download a folder?

**Comment by NicKoehler** [comment]
I changed a lot of things in my last commit [ca58a50](https://github.com/NicKoehler/mediafire_bulk_downloader/commit/ca58a5005bf5d3f325e5e11cd567a19e07cea1d6), try it and see.

**Comment by dennisb1** [comment]
Wow thats quickly! Great! Just tested and noticed 2 things

```
[root@server test]# python3 mediafire1.py https://www.mediafire.com/folder/wy*******8
************** already exists, skipping
************** already exists, skipping
Deleted file or Dangerous File Blocked
Take a look if you want to be sure: https://www.mediafire.com/file/qq************
All downloads completed
Traceback (most recent call last):
  File "mediafire1.py", line 224, in <module>
    main()
  File "mediafire1.py", line 55, in main
    get_folders(match[0], args.threads)
  File "mediafire1.py", line 88, in get_folders
    get_folders(folder["folderkey"], folder["name"])
  File "mediafire1.py", line 78, in get_folders
    download_folder(folder_key, folder_name, threads_num)
  File "mediafire1.py", line 114, in download_folder
    threadLimiter = BoundedSemaphore(threads_num)
  File "/usr/lib64/python3.6/threading.py", line 467, in __init__
    Semaphore.__init__(self, value)
  File "/usr/lib64/python3.6/threading.py", line 382, in __init__
    if value < 0:
TypeError: '<' not supported between instances of 'str' and 'int'

```
1. Is the traceback normal? 
2. It dont sync the files inside a folder but only the root files

**Comment by NicKoehler** [comment]
No that wasn't normal, try my [last commit](https://github.com/NicKoehler/mediafire_bulk_downloader/commit/c8add093cfaf5547205068597fdffa9448b5b93a)

**Comment by dennisb1** [comment]
Perfectly! Works just as expected. Really great improvement this. 
Did i see it correctly that you can now also specify the output folder with this new commit?

**Comment by dennisb1** [comment]
Great job!
