### ISSUE TITLE
Output path

### ISSUE THREAD

**Issue by emresaracoglu** [NicKoehler/mediafire_bulk_downloader#3]
Hello,

Thank you for this great work! 
Is it possible to specify the path to download the file?

For example;
_python3 mediafire.py [LINK] [download_folder_path_in_server]_

Thanks

**Comment by NicKoehler** [comment]
Hi, you can see every options using:

```sh
python mediafire.py -h
```

To choose the output directory you must use the -o option

```sh
python mediafire.py <url> -o <path>
```

**Comment by emresaracoglu** [comment]
I forgot to look in the help section, **sorry**. 

By the way, will you offer a feature for a single file download? Like this link: 
```
root@serve:/var/www/mediafire_bulk_downloader# python3 mediafire.py https://www.mediafire.com/file/ip4wmkmme82d9c4
Invalid link
```

**Comment by NicKoehler** [comment]
It doesn't seems to be too difficult, I'll take a look tomorrow

**Comment by emresaracoglu** [comment]
@NicKoehler Thank you!

**Comment by NicKoehler** [comment]
@emresaracoglu I added the functionality to download a link to a file using the main thread

**Comment by emresaracoglu** [comment]
@NicKoehler it's great! Thank you for your work.
