### ISSUE TITLE
File names with invalid characters

### ISSUE THREAD

**Issue by ghost** [NicKoehler/mediafire_bulk_downloader#5]
I am trying to download a folder but some file names contained invalid characters (generated sometime probably before upload from the character `ü`. When I download them, I get the error
```
Exception in thread Thread-687 (download_file):
Traceback (most recent call last):
  File "C:\\\\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\\\\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\\\\mediafire.py", line 270, in download_file
    with open(filename, "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'Fl?gel Variationen op.12.pdf'
```
When I download the file manually the `?` is rendered as `�`.

Suggested solution: Make it replace invalid characters with something like `-`.

**Comment by NicKoehler** [comment]
Hi, can you post the folder link? Thanks
